server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teamflowproject
    username: admin
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: asdf
      password: asdf

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # 최적화 옵션
  # show_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
  operations-sorter: method

cloud:
  aws:
    credentials:
      access-key: AKIA4VDBMI2CILU6RW7G
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: teamflowbucket
